# POSTTEST 7

<h3> Indro Dwi Saputro <br>
    2009106099

## TENSORFLOW

<b>Import Modul

In [1]:
import numpy as np
import tensorflow as tf

<b>Membuat random tensor dengan shape 5:5

In [3]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[ 0.384662  ,  0.4798931 , -0.296617  ,  0.8446649 , -0.05656386],
       [-0.19741069, -0.5774506 ,  1.6412264 , -0.98428965, -1.2909033 ],
       [-1.174873  ,  0.93296856,  0.1479086 ,  0.17608076,  0.1366443 ],
       [-1.0608447 , -0.9398267 ,  0.15594244,  0.80956125,  0.44797543],
       [-1.1371651 ,  0.21056917,  0.15653613,  0.79251504, -0.7092714 ]],
      dtype=float32)

### Membuat prime tensor list bilangan prima dengan shape 5:5

In [4]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89, 97, 101], 
                           shape=[5, 5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)>

<b>Perhitungan aritmatika add

In [5]:
print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[  2.384662    3.4798932   4.703383    7.844665   10.943436 ]
 [ 12.802589   16.42255    20.641226   22.01571    27.709097 ]
 [ 29.825127   37.93297    41.147907   43.176083   47.136642 ]
 [ 51.939156   58.060173   61.15594    71.80956    73.447975 ]
 [ 77.86284    83.21057    89.15654    97.79252   100.290726 ]], shape=(5, 5), dtype=float32)


<b> Perhitungan aritmatika multiply

In [6]:
print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  0.769324     1.4396793   -1.483085     5.912654    -0.62220246]
 [ -2.566339    -9.81666     31.183302   -22.638662   -37.436195  ]
 [-36.421062    34.519836     6.0642524    7.5714726    6.422282  ]
 [-56.224766   -55.449776     9.512489    57.478848    32.702206  ]
 [-89.836044    17.477242    13.931716    76.87396    -71.636406  ]], shape=(5, 5), dtype=float32)


<b>Perhitungan aritmatika pow

In [7]:
print(tf.pow(random_tensor, prime_tensor))

tf.Tensor(
[[ 1.4796485e-01  1.1051812e-01 -2.2960440e-03  3.0675456e-01
  -1.8963983e-14]
 [-6.9154205e-10 -8.8257555e-05  1.2251844e+04 -6.9474763e-01
  -1.6440609e+03]
 [-1.4781502e+02  7.6750159e-02  9.3267481e-35  3.6780043e-33
   0.0000000e+00]
 [-2.2884693e+01 -2.5693288e-02  0.0000000e+00  3.0600580e-07
   3.4798140e-26]
 [-2.5707354e+04  0.0000000e+00  0.0000000e+00  1.5985592e-10
  -8.5517595e-16]], shape=(5, 5), dtype=float32)


<b>Perhitungan aritmatika divide

In [8]:
print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[ 0.192331    0.15996437 -0.0593234   0.12066641 -0.00514217]
 [-0.01518544 -0.03396768  0.08638034 -0.0427952  -0.04451391]
 [-0.03789913  0.02521537  0.00360753  0.0040949   0.00290733]
 [-0.02001594 -0.01592927  0.00255643  0.01140227  0.00613665]
 [-0.01439449  0.00253698  0.00175883  0.00817026 -0.00702249]], shape=(5, 5), dtype=float32)


<b> Perhitungan aritmatika math.log

In [9]:
print(tf.math.log(random_tensor, prime_tensor))

tf.Tensor(
[[-0.9553902  -0.73419195         nan -0.16881533         nan]
 [        nan         nan  0.49544376         nan         nan]
 [        nan -0.06938378 -1.9111608  -1.7368126  -1.9903741 ]
 [        nan         nan -1.8582683  -0.21126285 -0.8030169 ]
 [        nan -1.5579411  -1.8544685  -0.2325438          nan]], shape=(5, 5), dtype=float32)


<b> Nilai maximal dari random_tensor

In [10]:
print("value random tensor:",random_tensor.numpy())
max_random_1 = tf.argmax(random_tensor, axis = 0)
max_random_2 = tf.argmax(random_tensor, axis = 1)
print("maximum value berdasarkan kolom:",max_random_1.numpy())
print("maximum value berdasarkan baris:",max_random_2.numpy())

value random tensor: [[ 0.384662    0.4798931  -0.296617    0.8446649  -0.05656386]
 [-0.19741069 -0.5774506   1.6412264  -0.98428965 -1.2909033 ]
 [-1.174873    0.93296856  0.1479086   0.17608076  0.1366443 ]
 [-1.0608447  -0.9398267   0.15594244  0.80956125  0.44797543]
 [-1.1371651   0.21056917  0.15653613  0.79251504 -0.7092714 ]]
maximum value berdasarkan kolom: [0 2 1 0 3]
maximum value berdasarkan baris: [3 2 1 3 3]


<b> Nilai minimal dari random_tensor

In [11]:
print("value random tensor:",random_tensor.numpy())
min_random_1 = tf.argmin(random_tensor, axis = 0)
min_random_2 = tf.argmin(random_tensor, axis = 1)
print("minimum value berdasarkan kolom:",min_random_1.numpy())
print("minimum value berdasarkan baris:",min_random_2.numpy())

value random tensor: [[ 0.384662    0.4798931  -0.296617    0.8446649  -0.05656386]
 [-0.19741069 -0.5774506   1.6412264  -0.98428965 -1.2909033 ]
 [-1.174873    0.93296856  0.1479086   0.17608076  0.1366443 ]
 [-1.0608447  -0.9398267   0.15594244  0.80956125  0.44797543]
 [-1.1371651   0.21056917  0.15653613  0.79251504 -0.7092714 ]]
minimum value berdasarkan kolom: [2 3 0 1 1]
minimum value berdasarkan baris: [2 4 0 0 0]


<h1> Concatenation
<h2> Penggabungan variable random_tensor & prime_tensor

In [12]:
print("size original data:",random_tensor.shape,prime_tensor.shape)
concated_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("size concatenated data:",concated_tensor.shape)

size original data: (5, 5) (5, 5)
size concatenated data: (10, 5)


<b> Sorting descending variable random_tensor & prime_tensor

In [17]:
print("value random tensor: \n",random_tensor.numpy())
print("value prime tensor: \n",prime_tensor.numpy())
sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("random tensor sorted dengan descending order:\n",sorted_random.numpy())
sorted_prime = tf.sort(prime_tensor, direction = "DESCENDING")
print("prime tensor sorted dengan descending order:\n",sorted_prime.numpy())


value random tensor: 
 [[ 0.384662    0.4798931  -0.296617    0.8446649  -0.05656386]
 [-0.19741069 -0.5774506   1.6412264  -0.98428965 -1.2909033 ]
 [-1.174873    0.93296856  0.1479086   0.17608076  0.1366443 ]
 [-1.0608447  -0.9398267   0.15594244  0.80956125  0.44797543]
 [-1.1371651   0.21056917  0.15653613  0.79251504 -0.7092714 ]]
value prime tensor: 
 [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]
random tensor sorted dengan descending order:
 [[ 0.8446649   0.4798931   0.384662   -0.05656386 -0.296617  ]
 [ 1.6412264  -0.19741069 -0.5774506  -0.98428965 -1.2909033 ]
 [ 0.93296856  0.17608076  0.1479086   0.1366443  -1.174873  ]
 [ 0.80956125  0.44797543  0.15594244 -0.9398267  -1.0608447 ]
 [ 0.79251504  0.21056917  0.15653613 -0.7092714  -1.1371651 ]]
prime tensor sorted dengan descending order:
 [[ 11.   7.   5.   3.   2.]
 [ 29.  23.  19.  17.  13.]
 [ 47.  43.  41.  37.  31.]
 [ 73